language: python
dist: jammy
os: linux
python:
- '3.11'
install:
- pip install -r requirements.txt
script:
# clone repo
- git clone --depth 1 https://github.com/weaviate/weaviate-io.git
# Add data to hubspot
- travis_wait 60 python3 ./import.py $PWD/weaviate-io /developers/weaviate /blog
